#!/usr/bin/env python
# -*- coding: utf-8 -*-
# GMate - Plugin Based Programmer's Text Editor
# Copyright © 2008-2009 Alexandre da Silva
#
# This file is part of Gmate.
#
# See LICENTE.TXT for licence information

# TODO: Start Gmate Process Here

import sys

from GMATE.main import Gmate
from GMATE import utils

def initialize():
    utils.setup_directories()

if __name__ == "__main__":
    file_uri = None
    initialize()
    gmate = Gmate()
    args = sys.argv[1:]
    if len(args) > 0:
        file_uri = args[0]
    gmate.run(file_uri)

